import type { Metadata } from "next";
import { ThemeProvider } from '@/context/ThemeContext';
import Sidebar from '@/app/components/Sidebar';

export const metadata: Metadata = {
  title: "Area Clientes",
  description: "Generated by @BrightInnovations",
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <div>
        <ThemeProvider>
          <div className="flex dark:bg-gray-900 text-gray-900 dark:text-gray-100">
            <Sidebar />
            <div className="p-10 flex-1">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </div>
  );
}
