import type { Metadata } from "next";
import "./globals.css";
// import { ThemeProvider } from '@/context/ThemeContext';
//hostinger: joaquinefarah@gmail.com dtex2024
export const metadata: Metadata = {
  title: "Area Clientes",
  description: "Generated by @BrightInnovations",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <ThemeProvider> */}
          <div>
            <main>
              {children}
            </main>
          </div>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
