import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '../styles/globals.css';
import { ThemeProvider } from './context/ThemeContext';
import Sidebar from './components/Sidebar';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Area Clientes",
  description: "Generated by @BrightInnovations",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <div className="flex">
            <Sidebar />
            <main className="p-10 flex-1">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
